### PR TITLE
APM-1016 Tear down infra post PR

### PR DESCRIPTION
**Pull request by Sourceless**
## Summary
* :robot: Tears down review sandboxes post PR

Add any other relevant notes or explanations here. **Remove this line if you have nothing to add.**

## Reviews Required
* [x] Dev
* [ ] Test
* [ ] Tech Author
* [ ] Product Owner

## Review Checklist
:information_source: This section is to be filled in by the **reviewer**.

* [ ] I have reviewed the changes in this PR and they fill all or part of the acceptance criteria of the ticket, and the code is in a mergeable state.
* [ ] If there were infrastructure, operational, or build changes, I have made sure there is sufficient evidence that the changes will work.
* [ ] I have ensured the changelog has been updated by the submitter, if necessary.

### CODE REVIEW

**Comment by Sourceless** [comment]
Closing to test teardown

**Comment by Sourceless** [comment]
Closing to test pipeline

**Comment by gjugpal** [comment]
Opening PR to test tearDown

**Comment by Sourceless** [comment]
Failed PR due to lack of hosted target availability, I'm going to force merge it anyway because it has succeeded in the past before any changes existed.

**Pull request merged**
